[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
logfile_maxbytes=50MB
logfile_backups=10

[program:langflow]
command=/usr/sbin/runuser -u user -- langflow run --host %(ENV_LANGFLOW_HOST)s --port %(ENV_LANGFLOW_BACKEND_PORT)s
autostart=true
autorestart=true
stopsignal=TERM
startsecs=5
stdout_logfile=/var/log/supervisor/langflow.stdout.log
stderr_logfile=/var/log/supervisor/langflow.stderr.log
environment=LANGFLOW_PORT="%(ENV_LANGFLOW_BACKEND_PORT)s"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stopsignal=QUIT
stdout_logfile=/var/log/supervisor/nginx.stdout.log
stderr_logfile=/var/log/supervisor/nginx.stderr.log
